package Cliente;
import Base.FachadaBase;
import Servidor.*;
import java.rmi.RemoteException;

/**
 * Interfaz Inicial para el inicio o registro de un usuario. A su vez se permite
 * el cambio de contrasenha por parte de un usuario
 * @author Marcos Garcia y Daniel Fuentes
 */
public class VInicio extends javax.swing.JFrame {
    
    private ServidorP2PInterfaz servidor;
    private ClienteP2PInterfaz usuario;
    private FachadaBase FachadaBase;
    
    public VInicio( ServidorP2PInterfaz h, FachadaBase FachadaBase) throws RemoteException {
        this.servidor = h;
        this.usuario = new ClienteP2PImpl(FachadaBase,h);
        this.FachadaBase = FachadaBase;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JButton();
        Registro = new javax.swing.JButton();
        Cambio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inicio.setText("Iniciar Sesión");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        Registro.setText("Registrarse");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });

        Cambio.setText("Cambiar contraseña");
        Cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(Cambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Inicio)
                .addGap(18, 18, 18)
                .addComponent(Registro)
                .addGap(18, 18, 18)
                .addComponent(Cambio)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed

        VRegistro vr = new VRegistro(this,servidor,usuario, FachadaBase);
        vr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistroActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        VIniciarSesion vi = new VIniciarSesion(this,servidor,usuario,FachadaBase);
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InicioActionPerformed

    private void CambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioActionPerformed
        VCambio1 c1 = new VCambio1(FachadaBase, this);
        c1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CambioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cambio;
    private javax.swing.JButton Inicio;
    private javax.swing.JButton Registro;
    // End of variables declaration//GEN-END:variables
}
