package Cliente;

import Base.FachadaBase;
import Servidor.ServidorP2PInterfaz;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Interfaz para aceptar y visualizar peticiones de amistad
 * @author Marcos Garcia y Daniel Fuentes
 */
public class VPeticiones extends javax.swing.JFrame {

    private final DefaultListModel modeloLista; 
    private String nombre;
    private FachadaBase FachadaBase;
    private VChat vc;
    private ServidorP2PInterfaz servidor;
            
    public VPeticiones(String nombre, FachadaBase FachadaBase, VChat vc, ServidorP2PInterfaz servidor) {
        this.nombre = nombre;
        this.FachadaBase = FachadaBase;
        initComponents();
        setLocationRelativeTo(null);
        this.vc = vc;
        this.servidor = servidor;
        this.modeloLista = new DefaultListModel();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        actualizarLista();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Atras = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Peticiones = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(Peticiones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Atras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Aceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(Aceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        try {
            int index = Peticiones.getSelectedIndex();
            String amigo = (String) modeloLista.getElementAt(index);
            System.out.println(amigo);
            if(FachadaBase.anadirAmigo(nombre, amigo)){
                servidor.nuevoAmigo(nombre, amigo);
                servidor.nuevoAmigo(amigo, nombre);
                actualizarLista();
                JOptionPane.showMessageDialog(null,"AMIGO AÑADIDO!!! :).\n", "AMIGO AÑADIDO", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,"NO SE HA PODIDO AÑADIR AL AMIGO\n", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(VPeticiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void actualizarLista(){
        
        ArrayList<String> peticiones = FachadaBase.listaPeticiones(nombre);
        
        modeloLista.clear();
        
        try{
           for(int i = 0; i < peticiones.size(); i++){
                modeloLista.addElement(peticiones.get(i));
               
           } 
           Peticiones.setModel(modeloLista);
        }
        catch(Exception e){
            System.out.println("Error en el combobox: " + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Atras;
    private javax.swing.JList<String> Peticiones;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
